name: Run Pester Tests

on:
  workflow_dispatch: # Manual trigger support

jobs:
  pester-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install PowerShell
    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https software-properties-common
        wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y powershell
        pwsh --version # Verify installation

    # Install Pester
    - name: Install Pester
      run: |
        pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser"
        pwsh -Command "Import-Module Pester"

    # Run Pester Tests
    - name: Run Pester Tests
      run: |
        pwsh -Command "Invoke-Pester -Path ./Tests -Output Detailed"
