name: Run Pester Tests

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  pester-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Pester
    - name: Install Pester
      run: |
        pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser"
        pwsh -Command "Import-Module Pester"

    # Run Pester Tests
    - name: Run Tests via invoke.ps1
      run: |
        pwsh -File ./Tests/invoke.ps1
