name: Development Environment Validation

on:
  workflow_dispatch:

jobs:
  validate-environment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Install Dependencies
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y nodejs npm
    #     curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    #     sudo apt-get install -y azure-cli
    #     sudo apt-get install -y openjdk-11-jdk docker.io

    - name: Verify Versions
      run: |
        node --version
        npm --version
        az --version
        java --version
        docker --version

    - name: Run Pester Tests
      run: |
        pwsh -Command "Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser"
        pwsh -Command "Invoke-Pester -Path ./Tests -Output Detailed"
